version: "3"
services:
  db:
    container_name: ohutils_production_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ohutils_production
      MYSQL_USER: ohutils
      MYSQL_PASSWORD: ${OHUTILS_DATABASE_PASSWORD}
    volumes:
      - ohutils_production_db_data:/var/lib/mysql
  app:
    container_name: ohutils_production
    image: ohutils_production
    build:
      context: ../../..
      dockerfile: ./config/docker/production/Dockerfile
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
        - RAILS_PRODUCTION_KEY=${RAILS_PRODUCTION_KEY}
        - OHUTILS_DATABASE_PASSWORD=${OHUTILS_DATABASE_PASSWORD}
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      OHUTILS_DATABASE_HOST: db
      OHUTILS_DATABASE_PASSWORD: ${OHUTILS_DATABASE_PASSWORD}
    ports:
      - ${PORT}:3000
    volumes:
      - ohutils_production_log_data:/app/log
    depends_on:
      - db
volumes:
  ohutils_production_log_data:
  ohutils_production_db_data:
